config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :crawls, except: [:edit]
  resources :rounds, only: :update
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :rounds
end

app/models/crawl.rb
class Crawl < ActiveRecord::Base
  belongs_to :user
  has_many :rounds
  has_many :pubs, through: :rounds
  has_many :challenges, through: :rounds

  def self.get_pubs postcode
    self.yelp_pubs_near(postcode).shuffle[0..8].map do |pub|
        Pub.find_by(
                      name: pub.name,
                      location: pub.location.postal_code
                    ) ||
        Pub.create(
                    name: pub.name,
                    location: pub.location.postal_code,
                    address: pub.location.display_address,
                    longitude: pub.location.coordinate.longitude,
                    latitude: pub.location.coordinate.latitude
                  )
    end
  end

  def self.get_challenges
    Challenge.all.shuffle[0..8]
  end

  private

  def self.yelp_pubs_near postcode
    Yelp.client.search(postcode, { term: 'bars and pubs', radius_filter: 800 }).businesses
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  # def self.send_messages
  #   self.all.each do | notification |
  #     self.send_message(notification.number)
  #   end
  # end


    def self.send_messages
      notifications = [{ number: '+447813881269' }]

      notifications.each do | notification |
        self.send_message(notification[:number])
      end
    end


  # def self.to_send
  #   self.all.each do | notification |
  #     if Time.now >= notification.send_at_time
  #       self.send_message(notification.number)
  #       self.delete(notification.id)
  #     end
  #   end
  # end


  def self.send_message(tel_number)
    client = Twilio::REST::Client.new ENV['ACCOUNT_SID'], ENV['AUTH_TOKEN']
    client.account.messages.create(
      from: ENV['TWILIO_NUMBER'],
      to:   tel_number,
      body: "Time is up, next pub!"
    )
  end

  def self.new_message(round)
    time = Time.now + (round.challenge.time_allocation * 60)
    self.create(number: round.crawl.mob_number,
                send_at_time: time )
  end
end

app/models/pub.rb
class Pub < ActiveRecord::Base
  has_many :rounds
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :pub
	belongs_to :crawl
	belongs_to :challenge

	def self.log_time id
		Round.update(id, checkin: Time.now)
	end

	def self.reveal id
		Round.update(id.to_i, visible: true)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :crawls
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    if current_user
      @crawls = current_user.crawls
      render json: @crawls
    end
  end

  def show
    @crawl = Crawl.find params[:id]
    render json: @crawl, include: [:pubs, :rounds, :challenges]
  end

  def create
    if current_user
      crawl = Crawl.new crawl_params
      if crawl.save
        current_user.crawls << crawl
        pubs = Crawl.get_pubs(crawl.start_postcode)
        challenges = Crawl.get_challenges

        rounds = pubs.map.with_index do |pub, index|
          Round.create(
                        pub_id: pub.id,
                        challenge_id: challenges[index].id,
                        visible: (index == 0)
                      )
        end

        crawl.rounds << rounds

        render :json => { :status => "success", :message => crawl }, :status => 200
      else
        render :json => { :errors => crawl.errors.full_messages }
      end

    end
  end

  private

  def crawl_params
    params.require(:crawl).permit :name, :start_postcode
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
skip_before_action :verify_authenticity_token

	def update
		round = Round.find params[:id]
		if !round.visible
			Round.reveal params[:id]
		else
			Round.log_time params[:id]
		end
		render :json => { :status => "success", :message => round.crawl}, :status => 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/crawls_helper.rb
module CrawlsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/crawls/index.html.erb
<h1>All Crawls</h1>

<% @crawls.each do |crawl| %>
  <%= link_to crawl.name, crawl_path(crawl) %>
<% end %>

<%= link_to 'New Crawl', new_crawl_path %>

app/views/crawls/new.html.erb
<%= form_for @crawl, url: {action: "create"}, html: {class: "crawl-form"} do |f| %>
  <%= f.label :name_your_crawl %>:
  <%= f.text_field :name %>
  <%= f.label :start_postcode %>:
  <%= f.text_field :start_postcode %>
  <%= f.submit "Create" %>
<% end %>

app/views/crawls/pub.html.erb
<h1>Your Pub!</h1>

<p class='pub-name'>
  <%= @pub.name %>
</p>

<ul class='pub-address'>
  <% @pub.location.display_address.each do |line| %>
    <li>
      <%= line %>
    </li>
  <% end %>
</ul>

app/views/crawls/show.html.erb
<%= @crawl.name %>

<h1>Your Pubs!</h1>

<ul>
  <% @crawl.rounds.each do |round| %>
    <% if round.visible %>
      <li class="pub-name">
        <label for="pub-name" class="pub">Pub Name:</label>
        <%= round.pub.name %>
      </li>

      <label for="pub-address">Pub Address:</label>
      <% round.pub.address.each do |line| %>
        <li class="pub-address"><%= line %></li>
      <% end %>
      <% if !round.checkin %>
        <form method="post" action="/rounds/<%= round.id %>">
          <input type="hidden" name="_method" value="put">
          <button type="Submit">Check in</button>
        </form>
      <% end %>
    <% end %>
  <% end %>
</Ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pubcrawler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>